# Scala.js Project Template with Tyrian and Flowbite

This project is generated by [template](https://github.com/linux-root/tyrian-flowbite.g8)

### Prerequisites

- [Java JDK](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html) (11 or higher)
- [sbt](https://www.scala-sbt.org/download.html) (Scala Build Tool)
- [Nodejs V22.13.0](https://nodejs.org/en/blog/release/v22.13.0)

## Getting Started

### 1. Show all useful commands

```bash
sbt
```

### 2. Start Vite dev server on `http://localhost:9876`

```bash
sbt fe dev
```

### 3. Build static web

```bash
sbt fe dst
```

## Template license

Written in 2024 by Watson Dinh <ping@w47s0n.com>

To the extent possible under law, the author(s) have dedicated
all copyright and related and neighboring rights to this template
to the public domain worldwide. This template is distributed without
any warranty. See <https://creativecommons.org/publicdomain/zero/1.0/>.
[g8]: <https://www.foundweekends.org/giter8/>
